# Generated by Django 2.2 on 2020-05-20 10:04

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('expected_ctc', models.PositiveIntegerField()),
                ('current_ctc', models.PositiveIntegerField(blank=True, null=True)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('job_title', models.CharField(choices=[('sde1', 'SDE 1'), ('sde2', 'SDE 2'), ('graphic_designer', 'Graphic Designer'), ('hr', 'HR'), ('tech_lead', 'Tech Lead')], max_length=50)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
